name: Test Cron

on:
    schedule:
        - cron: '*/1 * * * *' # Runs every minute

jobs:
    test-cron:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Print current UTC time
              run: |
                  echo "Current UTC time: $(date -u)"
                  echo "This step confirms if cron triggers correctly"
